Store/urls.py
from django.conf.urls import include, url

from .views import ListStore, StoreView, StoreDetailView, ProductListView

urlpatterns = [
    url(r'^list/store$', ListStore.as_view(), name='list-store'),
    url(r'^store$', StoreView.as_view(), name='store-list'),
    url(r'^store/(?P<token>[0-9a-z]+)$', StoreView.as_view(), name='store-detail'),
    url(r'^product$', ProductListView.as_view(), name='product-list'),
]

nepstore/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^', include('pages.urls', namespace='pages')),
    url(r'^', include('Store.urls', namespace='store')),
    url(r'^api/v1/', include('Store.urls', namespace='store-api')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block head_title %}NepMart{% endblock head_title%}</title>
    <link href="{% static  "css/semantic-ui.min.css" %}" type="text/css" rel="stylesheet">
    <link href="{% static  "css/nepmart.css" %}" type="text/css" rel="stylesheet">
  </head>
  <body>
    <div class="ui top attached demo menu nav-menu">
      <div class="ui container nav-container">
        <a class="item">
          <i class="sidebar icon"></i>
          NepMart
        </a>
      </div>
    <div class="right menu nav-right-items">
    {% if request.user.is_authenticated %}
      <a class="ui item" href='{% url 'account_logout' %}'>
        Logout
       </a>
    {% else %}
      <a class="ui item" href='{% url 'account_login' %}'>
        Login
       </a>
     {% endif %}
      <a class="ui basic animated fade button nav-post-btn" tabindex="0" href="{% url 'store:list-store' %}">
      <div class="visible content">List your Store</div>
        <div class="hidden content">
          Its Free
        </div>
      </a>
    </div>
    </div>
      <div class="ui bottom attached segment pushable">
        <div class="ui inverted labeled icon left inline vertical sidebar menu">
          <a class="item">
            <i class="home icon"></i>
            Home
          </a>
          <a class="item">
            <i class="block layout icon"></i>
            Topics
          </a>
          <a class="item">
            <i class="smile icon"></i>
            Friends
          </a>
          <a class="item">
            <i class="calendar icon"></i>
            History
          </a>
        </div>
        <div class="pusher">
          {% block body %}

          {% endblock body %}
        </div>
        <!-- <div class="footer">
        <a href="http://www.freepik.com/free-photos-vectors/background">Background image created by Snowing - Freepik.com</a>
        </div> !-->
    </div>
    {% block js %}
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/semantic-ui.min.js' %}"></script>
      <script src="{% static 'js/nepstore.js' %}"></script>
    {% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="ui basic segment">
  <section class="header-row">
  </section>
</div>
{% endblock body %}